### PR TITLE
Update Hercules EPIC accounts

### PR DESCRIPTION
**Pull request by zach1221**
## Description

Updating the Hercules EPIC accounts to /work/noaa/epic/role-epic from role-epic-ps

### Input data additions/changes
- [ ] No changes are expected to input data.
- [ ] Changes are expected to input data:
  - [ ] New input data.
  - [ ] Updated input data.

### Anticipated changes to regression tests:
- [ ] No changes are expected to any regression test.
- [ ] Changes are expected to the following tests:

## Subcomponents involved:
- [ ] AQM
- [ ] CDEPS
- [ ] CICE
- [ ] CMEPS
- [ ] CMakeModules
- [ ] FV3
- [ ] GOCART
- [ ] HYCOM
- [ ] MOM6
- [ ] NOAHMP
- [ ] WW3
- [ ] stochastic_physics
- [ ] none

## Commit Queue Checklist:

- [ ] Link PR's from all sub-components involved in section below
- [ ] Confirm reviews completed in ALL sub-component PR's
- [ ] Add all appropriate labels to this PR.
- [ ] Run full RT suite on either Hera/Cheyenne AND attach log to a PR comment.
- [ ] Add list of any failed regression tests to "Anticipated changes to regression tests" section.

## Testing Day Checklist:

- [ ] This PR is up-to-date with the top of all sub-component repositories except for those sub-components which are the subject of this PR.
- [ ] Move new/updated input data on RDHPCS Hera and propagate input data changes to all supported systems.

### Testing Log (for CM's):
- RDHPCS
  - [ ] Hera
  - [ ] Orion
  - [ ] Jet
  - [ ] Gaea
  - [ ] Cheyenne
- WCOSS2
  - [ ] Dogwood/Cactus
  - [ ] Acorn
- CI
  - [ ] Completed
- opnReqTest
  - [ ] N/A
  - [ ] Log attached to comment

### CODE REVIEW

**Comment by ulmononian** [comment]
@zach1221 just got this up to speed w/ devleop.

it looks like your PR wants to change 77 files, which seems off. what are the files that need to be changed for the hercules role account changes?

**Comment by zach1221** [comment]
@ulmononian I think those are just the changes I pushed to bring it up to date with ufs-community:develop. In any case, I added changes to **bl.py** and **rt.py** in tests/auto-jenkins/jobs. As well as **rt_auto_jenkins.py** and **start_rt_auto_jenkins.sh** in tests/auto-jenkins/. And finally I made some updates to **rt.sh** and **opnReqTest** scripts in /tests/ .

**Comment by ulmononian** [comment]
> @ulmononian I think those are just the changes I pushed to bring it up to date with ufs-community:develop. In any case, I added changes to **bl.py** and **rt.py** in tests/auto-jenkins/jobs. As well as **rt_auto_jenkins.py** and **start_rt_auto_jenkins.sh** in tests/auto-jenkins/. And finally I made some updates to **rt.sh** and **opnReqTest** scripts in /tests/ .

ok cool. can you revise your fork branch to only include the changes pertinent to hercules? right now, 77 files show different, so it won't merge properly.

another option would be delete this pr, merge denise's recent changes in your fork branch, then re-open a pr. then only those files modified for hercules will show as different and to-be merged.

**Comment by zach1221** [comment]
@ulmononian sure, no problem. Let me close this PR, then I'll make a new with only my changes. I'll let you know once it's finished.

**Comment by ulmononian** [comment]
sorry for the hassle, but thanks very much for doing this!!

**Pull request closed without merging**
